Issue 776: securityonion-elsa-extras: set version 3.3 in syslog-ng.conf

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -740,6 +740,8 @@ case "$1" in
 
 	                	SYSLOG_CONF="/etc/syslog-ng/syslog-ng.conf"
 
+				sed -i 's|^@version: 3.2$|@version: 3.3|g' $SYSLOG_CONF || echo "Error updating syslog-ng version from 3.2 to 3.3 in $SYSLOG_CONF."
+
         	            	if ! grep 'source s_bro_mysql { file("/nsm/bro/logs/current/mysql.log" flags(no-parse) program_override("bro_mysql")); };' $SYSLOG_CONF >> /dev/null; then
 					echo "* Updating $SYSLOG_CONF to monitor mysql.log."
 					sed -i '/^source s_bro_ssh/a source s_bro_mysql { file("/nsm/bro/logs/current/mysql.log" flags(no-parse) program_override("bro_mysql")); };' $SYSLOG_CONF || echo "Error adding s_bro_mysql to $SYSLOG_CONF."
