Issue 1010: securityonion-elsa-extras: Windows process enhancements

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -867,6 +867,31 @@ case "$1" in
 		touch $FILE
 	fi
 
+	# 2016-10-19 Windows process enhancements
+	UPDATE="2016-10-19"
+	FILE="/nsm/elsa/$UPDATE"
+	if [ ! -f $FILE ]; then
+		if grep -i "ELSA=yes" /etc/nsm/securityonion.conf >/dev/null 2>&1; then
+			echo "* ELSA is enabled on this box."
+			# Only update database if Setup has already been run
+			if [ -e /var/log/nsm/sosetup.log ]; then
+				echo "* Found sosetup.log."
+				echo "* Did NOT find $FILE, so applying $UPDATE database schema update."
+
+				# Store all SQL schema updates as files in $SQL_DIR
+				SQL_DIR="/opt/elsa/contrib/securityonion/contrib/sql"
+
+        	                echo "* Updating database schema."
+				SQL="$SQL_DIR/asa_botnet.sql"
+				mysql --defaults-file=/etc/mysql/debian.cnf < $SQL || echo "Error importing $SQL."
+				SQL="$SQL_DIR/win_process_tracking.sql"
+				mysql --defaults-file=/etc/mysql/debian.cnf < $SQL || echo "Error importing $SQL."
+			fi
+		fi
+		# Now that we've applied the update, record that we've applied it
+		touch $FILE
+	fi
+
 	# Always check to see if ELSA is enabled and, if so, update patterns
 	if grep -i "ELSA=yes" /etc/nsm/securityonion.conf >/dev/null 2>&1; then
 		echo "* ELSA is enabled on this box."
