Issue 796: securityonion-elsa-extras: Add script to fix ELSA syslogs_archive_1 issue

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -795,6 +795,12 @@ case "$1" in
 		service syslog-ng restart >/dev/null 2>&1 || echo "Error restarting syslog-ng."
 	fi
 
+	# Make sure that reset script is executable
+	FILE="/usr/bin/securityonion-elsa-reset-archive"
+	if [ -f $FILE ]; then
+		chmod +x $FILE || echo "Error making $FILE executable."
+	fi
+
         ;;
     abort-upgrade|abort-remove|abort-deconfigure)
         ;;
