only replace pipes for Bro logs

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -576,7 +576,7 @@ case "$1" in
 
 	                        if ! grep "^rewrite r_from_pipes" $CONF >> /dev/null; then
         	                        echo "* Updating $CONF with rewrite r_from_pipes."
-                	                sed -i "/^rewrite r_snare/a rewrite r_from_pipes { subst('\\\|', \"%7C\", value(\"MESSAGE\") flags(global)); };" $CONF || echo "Error adding rewrite r_from_pipes to $CONF."
+                	                sed -i "/^rewrite r_snare/a rewrite r_from_pipes { subst('\\\|', \"%7C\", value(\"MESSAGE\") flags(global) condition(program(\"bro_*\" type(glob)))); };" $CONF || echo "Error adding rewrite r_from_pipes to $CONF."
                         	        sed -i '/rewrite(r_snare);/a \\trewrite(r_from_pipes);' $CONF || echo "Error adding r_from_pipes to $CONF."
 	                        fi
 
