set Apache mpm_prefork_module MaxRequestsPerChild to 2

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -596,6 +596,19 @@ case "$1" in
 				service syslog-ng restart >/dev/null 2>&1 || echo "Error restarting syslog-ng."
 			fi
 
+			# Ensure that Apache has the right prefork settings
+			CONF="/etc/apache2/apache2.conf"
+			if [ -f $CONF ]; then
+			
+				CONFBAK="$CONF.$DATE"
+				echo "* Backing up $CONF to $CONFBAK."
+				cp $CONF $CONFBAK || echo "Error backing up $CONF to $CONFBAK."
+
+				echo "* Setting Apache mpm_prefork_module MaxRequestsPerChild to 2"
+				perl -le 'use Apache::Admin::Config; my $ap = new Apache::Admin::Config("$ARGV[0]"); my @ar = $ap->select(-name => "IfModule", -value => "mpm_preform_module"); use Data::Dumper; $ar[0]->directive("MaxRequestsPerChild")->set_value(2); $ap->save();' $CONF || echo "Error updating $CONF."
+
+			fi
+
 			# All boxes with ELSA enabled (masters and sensors) need /etc/elsa_web.conf migrated to 1205 format
 			CONF="/etc/elsa_web.conf"
 			if [ -f $CONF ]; then
