ELSA syslog-ng.conf rewrite r_pipes #447

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -556,32 +556,48 @@ case "$1" in
 		fi
 	fi
 
-	# Update /etc/elsa_web.conf for ELSA 1205
+	# Update to ELSA 1205
 	if [ "$2" = "20131117-1ubuntu0securityonion58" ] || [ "$2" = "20131117-1ubuntu0securityonion56" ] || [ "$2" = "20131117-1ubuntu0securityonion53" ] || [ "$2" = "20131117-1ubuntu0securityonion50" ] || [ "$2" = "20131117-1ubuntu0securityonion45" ] || [ "$2" = "20131117-1ubuntu0securityonion43" ] || [ "$2" = "20131117-1ubuntu0securityonion41" ] || [ "$2" = "20131117-1ubuntu0securityonion36" ] || [ "$2" = "20131117-1ubuntu0securityonion28" ] || [ "$2" = "20131117-1ubuntu0securityonion25" ] || [ "$2" = "20131117-1ubuntu0securityonion19" ]; then
 
-		# All boxes with ELSA enabled (masters and sensors) need /etc/elsa_web.conf migrated to 1205 format
-		CONF="/etc/elsa_web.conf"
-		# Only update /etc/elsa_web.conf if Setup has already been run
-		if [ -f /var/log/nsm/sosetup.log ] && [ -f $CONF ]; then
+		# Only update if Setup has already been run
+		if [ -f /var/log/nsm/sosetup.log ] ; then
 
-			check_config_perms
-			
-			DATE=`date '+%Y%m%d'`
-			CONFBAK="$CONF.$DATE"
-			echo "Backing up $CONF to $CONFBAK."
-			cp $CONF $CONFBAK || echo "Error backing up $CONF to $CONFBAK."
-			/usr/bin/securityonion_elsa_register.rb --migrate-web-1205 || echo "Error updating $CONF for ELSA 1205."
+			# Issue 447: rewrite pipes in Bro logs
+			SYSLOG_CONF="/etc/syslog-ng/syslog-ng.conf"
+			if [ -f $CONF ]; then
+	                        if ! grep "^rewrite r_from_pipes" $SYSLOG_CONF >> /dev/null; then
+        	                        echo "* Updating $SYSLOG_CONF with rewrite r_from_pipes."
+                	                sed -i "/^rewrite r_snare/a rewrite r_from_pipes { subst('\\\|', \"%7C\", value(\"MESSAGE\") flags(global)); };" $SYSLOG_CONF || echo "Error adding rewrite r_from_pipes to $SYSLOG_CONF."
+                        	        sed -i '/rewrite(r_snare);/a \\trewrite(r_from_pipes);' $SYSLOG_CONF || echo "Error adding r_from_pipes to $SYSLOG_CONF."
+	                        fi
 
-			echo "* Restarting ELSA web server."
-			# Is this a master server or a sensor-only box?
-			if [ -d /var/lib/mysql/securityonion_db ]; then
-				# This is a master server, so restart Apache
-				apache2ctl restart || echo "Error restarting Apache."
-			else
-				if [ -f /etc/init.d/starman ]; then
-				# This is a sensor-only box, so restart starman
-				/etc/init.d/starman stop || echo "Error stopping starman."
-				/etc/init.d/starman start || echo "Error starting starman."
+				echo "* Restarting syslog-ng."
+				service syslog-ng restart >/dev/null 2>&1 || echo "Error restarting syslog-ng."
+			fi
+
+			# All boxes with ELSA enabled (masters and sensors) need /etc/elsa_web.conf migrated to 1205 format
+			CONF="/etc/elsa_web.conf"
+			if [ -f $CONF ]; then
+
+				check_config_perms
+				
+				DATE=`date '+%Y%m%d'`
+				CONFBAK="$CONF.$DATE"
+				echo "Backing up $CONF to $CONFBAK."
+				cp $CONF $CONFBAK || echo "Error backing up $CONF to $CONFBAK."
+				/usr/bin/securityonion_elsa_register.rb --migrate-web-1205 || echo "Error updating $CONF for ELSA 1205."
+
+				echo "* Restarting ELSA web server."
+				# Is this a master server or a sensor-only box?
+				if [ -d /var/lib/mysql/securityonion_db ]; then
+					# This is a master server, so restart Apache
+					apache2ctl restart || echo "Error restarting Apache."
+				else
+					if [ -f /etc/init.d/starman ]; then
+					# This is a sensor-only box, so restart starman
+					/etc/init.d/starman stop || echo "Error stopping starman."
+					/etc/init.d/starman start || echo "Error starting starman."
+					fi
 				fi
 			fi
 
